// Generated by Wrangler by running `wrangler types`

interface Env {
	AUTH0_DOMAIN: string;
	AUTH0_CLIENT_ID: string;
	AUTH0_CLIENT_SECRET: string;
	AUTH0_CALLBACK_URL: string;
	AUTH0_LOGOUT_URL: string;
	AUTH0_RETURN_TO_URL: string;
	SESSION_SECRET: string;
	CF_PAGES_URL: string;
}
