// Generated by Wrangler by running `wrangler types`

interface Env {
	AUTH0_DOMAIN: string;
	AUTH0_CLIENT_ID: string;
	AUTH0_CLIENT_SECRET: string;
	AUTH0_CALLBACK_URL: string;
	CF_PAGES_URL: string;
	SESSION_SECRET: string;
	FORM_URL: string;
	FORM_TOKEN_KEY: string;
	DEFAULT_ADMINS: string;
	DB: D1Database;
}
