#:schema node_modules/wrangler/config-schema.json
name = "meibo-system-v3"
compatibility_date = "2024-12-20"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "meibo-system-v3-db"
database_id = "cf2c7299-068d-400a-8996-185781cd8763"
